
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: stg_orders
      description: "Staging model for the orders data."
      columns:
           - name: order_id
             description: "Primary key for the order."
           - name: customer_id
             description: "ID of the customer placing the order."
           - name: order_date
             description: "Date when the order was placed."
           - name: producr_id
             description: "ID of the product placed by the customer."
